ERP.Inventory/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Inventory.Controllers
{
    public class FormController : Controller
    {
        // GET: Form
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FormView(string pageName, string itemType)
        {
            ViewBag.ItemType = itemType;

            return PartialView($"~/Views/Form/_{pageName}.cshtml");
        }
    }
}

ERP.Inventory/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Inventory.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ERP.Inventory/Controllers/InvController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Inventory.Controllers
{
    public class InvController : Controller
    {
        // GET: Inv
        public ActionResult Index()
        {
            return View();
        }
    }
}

ERP.Inventory/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Inventory.Controllers
{
    public class StocksController : Controller
    {
        // GET: Stocks
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StockEntry()
        {
            return View("~/Views/Stocks/_StocksEntry.cshtml");
        }

        public ActionResult StockOut()
        {
            return View("~/Views/Stocks/_StocksOut.cshtml");
        }
    }
}

ERP.Inventory/Views/Form/Index.cshtml
@{ 
    ViewBag.Title = "Forms Page";
}

<div class="row">
    <div class="col-md-12">
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "BlotterForm" })" data-modal-size="true" id="Blotter Form" class="open-dialog btn btn-light">Blotter Form</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "BorrowersSlip" })" data-modal-size="true" id="Borrowers Slip" class="open-dialog btn btn-light">Borrowers Slip</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "GatePass" })" data-modal-size="false" id="Gate Pass" class="open-dialog btn btn-light">Gate Pass</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "IssuanceSlip" })" data-modal-size="true" id="Issuance Slip" class="open-dialog btn btn-light">Issuance Slip</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "PPERequestForm" })" data-modal-size="true" id="Employee PPE Request Form" class="open-dialog btn btn-light">Employee PPE Request Form</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "ItemDelivered", itemType = "tools" })" data-modal-size="true" id="Tools Delivered on Site" class="open-dialog btn btn-light">Tools Delivered on Site</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "ItemDelivered", itemType = "materials" })" data-modal-size="true" id="Materials Delivered on Site" class="open-dialog btn btn-light">Materials Delivered on Site</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "ItemDelivered", itemType = "Region" })" data-modal-size="true" id="Materials Delivered on Site" class="open-dialog btn btn-light">Materials Delivered on Site</a>
        <br />

        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "WithdrawalSlip" })" data-modal-size="true" id="Withdrawal Slip" class="open-dialog btn btn-light">Withdrawal Slip</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "ReceivingReport" })" data-modal-size="true" id="Receiving Report" class="open-dialog btn btn-light">Receiving Report</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "StockCard" })" data-modal-size="true" id="Stock Card" class="open-dialog btn btn-light">Stock Card</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "ToolsInventoryRecord" })" data-modal-size="true" id="Tools Inventory Record" class="open-dialog btn btn-light">Tools Inventory Record</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "MaterialsInventoryRecord" })" data-modal-size="true" id="Materials Inventory Record" class="open-dialog btn btn-light">Materials Inventory Record</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "ItemTransfered", itemType = "tools" })" data-modal-size="true" id="Tools Transfer Form" class="open-dialog btn btn-light">Tools Transfer Form</a>
        <a href="javascript:void(0)" data-href="@Url.Action("FormView", "Form", new { pageName = "ItemTransfered", itemType = "materials" })" data-modal-size="true" id="Materials Transfer Form" class="open-dialog btn btn-light">Materials Transfer Form</a>

    </div>
</div>

ERP.Inventory/Views/Form/_BlotterForm.cshtml
    <div class="row">
        <div class="col-md-12">
            <div class="custom-table-container" style="">
                <form action="#" method="post" autocomplete="off" class="blotter-form" data-action="">
                    <input type="hidden" name="DraftID" />
                    <input type="hidden" name="ID" value="@ViewBag.ID" />
                    <table class="custom-table">
                        <colgroup>
                            <col width="48" />
                            <col width="34" />
                            <col width="238" />
                            <col width="87" />
                            <col width="87" />
                            <col width="80" />
                            <col width="86" />
                            <col width="139" />
                        </colgroup>

                        <tr>
                            <td colspan="2" rowspan="3">
                                <img src="@Url.Content("~/Content/Images/Logo.png")" alt="Alternate Text" style="width:50px" />
                            </td>
                            <td colspan="3" class="text-center font-weight-bold" style="font-size:25px">
                                MARINAS & CO. BUILDERS INC.
                            </td>
                            <td></td>
                            <td colspan="2" class="bg-secondary text-center font-weight-bold py-2">
                                FM-FIN-INV-123
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-center">
                                2/F EPJ Bldg Basak Road Lapu Lapu City
                            </td>
                            <td></td>
                            <td>Control No.: </td>
                            <td>
                                <input type="text" name="ControlNumber" value="" />
                            </td>
                        </tr>
                        <tr>
                            <td colspan="6"></td>
                        </tr>
                        <tr>
                            <td colspan="2">Project Site: </td>
                            <td colspan="3">
                                <input type="text" name="ProjectSite" value="" />
                            </td>
                            <td></td>
                            <td>Date: </td>
                            <td>
                                <input type="text" name="Date" class="date-picker" value="" />
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">Address</td>
                            <td colspan="3">
                                <input type="text" name="Address" value="" />
                            </td>
                            <td colspan="3"></td>
                        </tr>
                        <tr>
                            <td colspan="2">Attention</td>
                            <td colspan="3">
                                <input type="text" name="Attention" value="" />
                            </td>
                            <td colspan="3"></td>
                        </tr>
                        <tr>
                            <td colspan="8" height="25"></td>
                        </tr>
                        <tr>
                            <td colspan="8" class="text-center font-weight-bold" style="font-size:25px">BLOTTER FORM</td>
                        </tr>
                        <tr>
                            <td colspan="8" height="25"></td>
                        </tr>
                        <tr>
                            <td class="text-center py-1 custom-table-border-solid" style="font-weight: 500">NO</td>
                            <td colspan="2" class="text-center py-1 custom-table-border-solid" style="font-weight: 500">ITEM DESCRIPTION</td>
                            <td class="text-center py-1 custom-table-border-solid" style="font-weight: 500">UNITS</td>
                            <td class="text-center py-1 custom-table-border-solid" style="font-weight: 500">QTY</td>
                            <td class="text-center py-1 custom-table-border-solid" style="font-weight: 500">UNIT PRICE</td>
                            <td class="text-center py-1 custom-table-border-solid" style="font-weight: 500">TOTAL AMOUNT</td>
                            <td class="text-center py-1 custom-table-border-solid" style="font-weight: 500">REMARKS</td>
                        </tr>


                        @*BODY*@

                        @for (var i = 0; i < 10; i++)
                        {
                            <tr class="blotteredItems">
                                <td class="custom-table-border-solid" height="25">
                                    <label style="width: 100%" class="text-center" name="number"></label>
                                </td>
                                <td colspan="2" class="custom-table-border-solid" height="25">
                                    <input type="text" class="text-center itemDescription" value="" style="border-bottom: none" />
                                </td>
                                <td class="custom-table-border-solid" height="25">
                                    <input type="text" class="text-center Units units" value="" name="Units" style="border-bottom: none" />
                                </td>
                                <td class="custom-table-border-solid" height="25">
                                    <input type="text" class="text-center quantity" value="" name="Quantity" style="border-bottom: none" />
                                </td>
                                <td class="custom-table-border-solid" height="25">
                                    <input type="text" class="text-center Price" name="Price" style="border-bottom: none" />
                                </td>
                                <td class="custom-table-border-solid" height="25">
                                    <input type="text" class="text-center totalAmount" name="TotalAmount" style="border-bottom: none" />
                                </td>
                                <td class="custom-table-border-solid" height="25">
                                    <input type="text" class="text-center remarks" value="" name="Remarks" style="border-bottom: none" />
                                </td>
                            </tr>
                        }
                        @*END BODY*@
                        <tr>
                            <td>
                                <small>Note:</small>
                            </td>
                            <td colspan="7"><small>Complete this copy with an attach Incident Report and submit to Inventory Department</small></td>
                        </tr>
                        <tr>
                            <td colspan="8" height="15"></td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                PREPARED BY: <br /> <br />
                                <input type="text" name="PreparedBy" style="width:70%" value="" />

                                <br />
                                <small>Warehouseman</small>
                            </td>
                            <td colspan="3">
                                RECEIVED/CHECKED BY: <br /> <br />
                                <input type="text" name="ReceivedBy" style="width:75%" value="" />
                                <br />
                                <small>&nbsp</small>
                            </td>
                            <td colspan="2">
                                APPROVED BY: <br /> <br />
                                <input type="text" name="ApprovedBy" value="" />
                                <br />
                                <small>Project In-Charge</small>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>

ERP.Inventory/Views/Form/_BorrowersSlip.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="custom-table-container"">
            <form action="#" method="post" autocomplete="off" class="borrowed-form">
                <input type="hidden" name="DraftID" />
                <input type="hidden" name="ID" value="@ViewBag.ID" />
                <table class="custom-table">
                    <colgroup>
                        <col width="10" />
                        <col width="78" />
                        <col width="200" />
                        <col width="148" />
                        <col width="68" />
                        <col width="142" />
                        <col width="152" />
                    </colgroup>
                    <tr>
                        <td colspan="3" rowspan="3">
                            <div class="d-flex">
                                <img src="@Url.Content("~/Content/Images/Logo.png")" alt="Alternate Text" style="height:50px; margin-right: 10px" />
                                <img src="@Url.Content("~/Content/Images/MCBI-TEXT.png")" alt="Alternate Text" style="height:50px" />
                            </div>
                        </td>
                        <td colspan="2" rowspan="3" class="text-center font-weight-bold" style="font-size:25px">BORROWER'S SLIP</td>
                        <td colspan="2" class="bg-secondary text-center text-white font-weight-bold">FM-FIN-INV-118</td>
                    </tr>
                    <tr>
                        <td>Ctrl No.: </td>
                        <td>
                            <input type="text" name="CtrlNumber" value="" />
                        </td>
                    </tr>
                    <tr>
                        <td>Date: </td>
                        <td>
                            <input type="text" class="date-picker" name="Date" value="" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7" height="15"></td>
                    </tr>
                    <tr>
                        <td colspan="2" class="text-center bg-secondary custom-table-border-solid py-2" style="font-weight: 500">NO</td>
                        <td colspan="3" class="text-center bg-secondary custom-table-border-solid py-2" style="font-weight: 500">DESCRIPTION</td>
                        <td class="text-center bg-secondary custom-table-border-solid py-2" style="font-weight: 500">QUANTITY</td>
                        <td class="text-center bg-secondary custom-table-border-solid py-2" style="font-weight: 500">UNITS</td>
                    </tr>

                    @*BODY*@

                    @for (var i = 0; i < 10; i++)
                    {
                        <tr class="borrowedItems">
                            <td colspan="2" class="custom-table-border-solid" height="25">

                                <label style="width: 100%" class="text-center" name="number"></label>
                            </td>
                            <td colspan="3" class="custom-table-border-solid" height="25">
                                <input type="text" name="Items" value=""  style="border-bottom: none"/>
                            </td>
                            <td class="custom-table-border-solid" height="25">
                                <input type="number" class="text-center quantity" name="Quantity" style="border-bottom: none" />
                            </td>
                            <td class="custom-table-border-solid" height="25">
                                <input type="text" class="text-center units" name="Units" style="border-bottom: none" />
                            </td>
                        </tr>

                    }

                    @*END BODY*@

                    <tr>
                        <td colspan="7" height="15"></td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            BORROWED BY: <br /> <br />
                            <input type="text" name="BorrowedBy" value="" />

                            <br />
                            <small>SIGNATURE OVER PRINTED NAME</small>
                        </td>
                        <td colspan="2"></td>
                        <td colspan="2">
                            APPROVED BY: <br /> <br />
                            <input type="text" name="ApprovedBy" value="" />

                            <br />
                            <small>SIGNATURE OVER PRINTED NAME</small>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7" class="pt-3">
                            <small>
                                Note: <br />
                                1.) Borrowed items must be properly, cleaned and in good condition. Otherwise damage item will be charge to borrowers. <br />
                                2.) This forms must have a return stamp with signature of borrower including the date of return, otherwise the item are considered not returned.
                            </small>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

ERP.Inventory/Views/Home/Index.cshtml
@{ 
    ViewBag.Title = "Home Page";
}

<div class="row">

    <div class="col-md-12">
        <small>Sample Text</small>
    </div>

</div>

ERP.Inventory/Views/Inv/Index.cshtml
@{
    ViewBag.Title = "Inv Page";
}

<p>Content Here!!</p>
<div class="form-group">
    <input type="hidden" name="ID" id="tagID" value="" />
    <input type="text" name="InventoryItem" class="form-control shadow-none" style="width: 50%" id="tags" value="" />
</div>







@*<div class="custom-table-container">
        <table class="custom-table">

            <colgroup>
                <col width="1" />
                <col width="6" />
                <col width="1" />
                <col width="1" />
                <col width="3" />

            </colgroup>

            <tr>
                <td class="custom-table-border-solid" height="15">no</td>
                <td class="custom-table-border-solid">des</td>
                <td class="custom-table-border-solid">qty</td>
                <td class="custom-table-border-solid">units</td>
                <td class="custom-table-border-solid">remarks</td>
            </tr>
        </table>
    </div>*@

ERP.Inventory/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" id="header">
    <div class="d-flex navbar-wrapper desktop-view">
        <div class="header-title text-center">
            <a class="navbar-brand" href="#">
                <span class="full-text">MCBI-Inventory</span>
                <span class="mini-text">MIMS</span>
            </a>
        </div>
        <!--FOR WEB-->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="mr-auto">
                <button type="button" id="sidebarCollapse" class="btn text-white shadow-none">
                    @*<i class="fa fa-close"></i>*@
                    <i class="lnr lnr-cross"></i>
                </button>
            </div>
            <div class="ml-auto">
                <span class="text-white" style="position: absolute; top: 2px; right: 10px; font-size: 85%">MCBI-Inventory Series @DateTime.Now.Year</span>
            </div>
        </div>
    </div>

</nav>

ERP.Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ERP.Inventory/Views/Shared/_Sidebar.cshtml
<nav id="sidebar">

    <ul class="list-unstyled">
        <li>
            <a href="#">
                @*<i class="fa fa-home"></i>*@
                <i class="lnr lnr-home"></i>
                Home
            </a>
        </li>
        <li class="">
            <a href="#inventorySubmenu" data-toggle="collapse" id="menu" aria-expanded="false" class="dropdown-toggle">
                @*<i class="fa fa-building"></i>*@
                <i class="lnr lnr-tag"></i> <!--Using -->
                Inventory
            </a>
            <ul class="collapse list-unstyled sidebarCollapse" id="inventorySubmenu">
                <li>
                    <a href="@Url.Action("StockEntry", "Stocks")" class="sub-menu">Item Stock Entry</a>
                </li>
                <li>
                    <a href="#" class="sub-menu">Item Stock Out</a>
                </li>
            </ul>
        </li>

        <li class="">
            <a href="#anotherSubMenu" data-toggle="collapse" id="anotherMenu" aria-expanded="false" class="dropdown-toggle">
                @*<i class="fa fa-building"></i>*@
                <i class="lnr lnr-bug"></i> <!--Using -->
                Another Menu
            </a>
            <ul class="collapse list-unstyled sidebarCollapse" id="anotherSubMenu">
                <li>
                    <a href="#" class="sub-menu">SubMenu 1</a>
                </li>
                <li>
                    <a href="#" class="sub-menu">SubMenu 2</a>
                </li>
            </ul>
        </li>

    </ul>

</nav>

ERP.Inventory/Views/Stocks/_StocksEntry.cshtml
@{
    ViewBag.Title = "Stocks Entry Page";
}

<div class="row">
    <div class="col-md-10 pt-3">

        @*<tr>
            <td colspan="2" class="text-right">Ctrl No.:</td>
            <td>
                <input type="text" name="CtrlNumber" value="" />
            </td>
        </tr>*@
        <div style="width:100%; height:2em">
            <input class="btn-success" type="submit" value="Edit" style="float:right; margin-right:2px">
            <input class="btn-danger" type="submit" value="Discard" style="float:right; margin-right:2px">
            <input class="btn-warning" type="submit" value="Save" style="float:right; margin-right:2px">
            @*<input class="ui-button" type="submit" value="Save" style="float:left">*@
        </div>
        @*<button class="btn-danger" style="margin-left:auto">DISCARD</button>
        <button class="btn-warning" style="margin-left:auto">EDIT</button>*@

        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="tds-tab" data-toggle="tab" href="#tds" role="tab" aria-controls="tds" aria-selected="true">Tools Delivered On Site</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="mds-tab" data-toggle="tab" href="#mds" role="tab" aria-controls="mds" aria-selected="false">Materials Delivered On Site</a>
            </li>
        </ul>


        <div class="tab-content mt-3" id="myTabContent">
            <div class="tab-pane fade show active" id="tds" role="tabpanel" aria-labelledby="tds-tab">
                @Html.Action("FormView", "Form", new { pageName = "ItemDelivered", itemType = "tools" })

            </div>
            <div class="tab-pane fade" id="mds" role="tabpanel" aria-labelledby="mds-tab">
                @Html.Action("FormView", "Form", new { pageName = "ItemDelivered", itemType = "materials" })

            </div>
        </div>
    </div>
    <div class="col-md-2 text-center" style="border: 1px solid; padding-top: 20px">
        <small>Panel</small>
    </div>

</div>


@section Scripts{

    <script>
        $(function () {

            $.ajaxSetup({
                async: false
            });

            //FOR PROJECTS
            var projects = [];

            var projectURL = 'http://124.105.198.3:82/api/v1/dssprojects/1/1000/0';

            $.getJSON(projectURL, function (data) {

                var dat = data.Data;

                for (var i = 0; i < dat.length; i++) {
                    //console.log(dat[i]);

                    var newObj = {};

                    newObj.id = dat[i].ID;
                    newObj.value = dat[i].ProjectName;
                    newObj.label = dat[i].ProjectNumber + ' - ' + dat[i].ProjectName;
                    newObj.projectNo = dat[i].ProjectNumber;

                    projects.push(newObj);
                }

            });

            $(".projectName").autocomplete({
                source: projects,
                select: function (event, ui) {

                    var $this = $(this);

                    //console.log(ui.item.id);
                    $this.parents('td').find('input.projectID').val(ui.item.id);
                    $this.parents('table').find('input.projectNumber').val(ui.item.projectNo);
                }
            });

            console.log("test");
            //FOR Region
            var Regions = [];

            var RegionURL = 'https://raw.githubusercontent.com/clavearnel/philippines-region-province-citymun-brgy/master/json/refregion.json';
            
            $.getJSON(RegionURL, function (data) {

                var dat = data.RECORDS;
                console.log(data);
                for (var x = 0; x < dat.length; x++) {
                    //console.log(dat[i]);

                    var newObj = {};

                    newObj.id = dat[x].ID;
                    newObj.value = dat[x].regDesc;
                    //newObj.label = dat[i].ProjectNumber + ' - ' + dat[i].ProjectName;
                    //newObj.label = dat[i].RegionNumber;

                    Regions.push(newObj); console.log(Regions)

                }

            });
            
            $(".regionName").autocomplete({
                source: Regions,
                select: function (event, ui) {

                    var $this = $(this);

                    //console.log(ui.istem.id);
                    $this.parents('td').find('input.regionID').val(ui.item.id);
                    //$this.parents('table').find('input.regionName').val(ui.item.value);
                }
            });



            //FOR ITEMS
            var items = [];

            var itemURL = 'http://192.168.1.100:89/api/values';

            $.getJSON(itemURL, function (data) {


                for (var i = 0; i < data.length; i++) {

                    var newObj = {};

                    newObj.id = data[i].ID;
                    newObj.value = data[i].Name;
                    newObj.label = data[i].Name;

                    items.push(newObj);

                }


            });

            //console.log(items);

            $('body').on('click', '.items', function () {

                $(this).autocomplete({
                    source: items,
                    select: function (event, ui) {

                        var $this = $(this);

                        // console.log(ui.item.id);

                        $this.parents('td').find('input.ItemID').val(ui.item.id);
                    }
                });

            });

        });

        $.ajaxSetup({
            async: true
        });
    </script>

}